# This file provides instructions for packaging.

`MooseX-RoleQR`
	perl_version_from m`MooseX::RoleQR`;
	version_from      m`MooseX::RoleQR`;
	readme_from       m`MooseX::RoleQR`;
	test_requires     p`Test::More 0.61`;
	requires          p`Moose 2.00`;
	requires          p`namespace::sweep`;
	requires          p`Scalar::Does 0.002`;
	requires          p`thanks`;
.

